
"""14aug(1-15)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaMVMoY5w8-Dh6Hkm1Zr__qpKy2kdQOA
"""

What is Python? Mention two of its key features.

High-level, interpreted programming language.

Features: (i) Easy to learn (readable syntax), (ii) Dynamically typed.

2. How do you write a single-line comment in Python?

# This is a comment


3. How do you write a multi-line comment in Python?

"""
This is
a multi-line
comment
"""


4. What is the difference between print() and return?

print() → displays output on screen.

return → sends value back from a function.

5. How do you get user input in Python?

name = input("Enter your name: ")


6. How do you check the version of Python installed?

python --version


7. Is Python case-sensitive? Give an example.
Yes.

a = 10
A = 20  # different variables


8. How do you run a Python script from the command line?

python filename.py


9. What are keywords in Python? How can you list them?

Reserved words (like if, else, class).

import keyword
print(keyword.kwlist)


10. How do you declare a variable in Python?

x = 5


11. What’s the difference between = and ==?

= → assignment.

== → comparison.

12. How do you swap two variables without using a third variable?

a, b = b, a


13. How do you write a one-line if statement?

x = 10
print("Yes") if x > 5 else print("No")


14. What’s the difference between None and 0 in Python?

None → absence of value.

0 → integer value.

15. What is indentation in Python and why is it important?

Spaces at line start → define code blocks.

Important because Python uses it instead of {}.